# Generated by Django 5.1 on 2024-08-23 01:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("toonkor_collector2", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="manhwa",
            name="slug",
            field=models.SlugField(default=""),
        ),
    ]
