# Generated by Django 5.1 on 2024-08-24 03:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("toonkor_collector2", "0002_manhwa_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chapter",
            name="date_upload",
        ),
        migrations.RemoveField(
            model_name="chapter",
            name="downloaded_path",
        ),
        migrations.RemoveField(
            model_name="chapter",
            name="translated_path",
        ),
        migrations.AddField(
            model_name="chapter",
            name="translated",
            field=models.BooleanField(default=False),
        ),
    ]
