# Generated by Django 5.1 on 2024-08-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("toonkor_collector2", "0003_remove_chapter_date_upload_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="manhwa",
            name="en_author",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name="manhwa",
            name="en_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="manhwa",
            name="en_title",
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
