# Generated by Django 5.1 on 2024-09-05 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toonkor_collector2", "0004_manhwa_en_author_manhwa_en_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chapter",
            name="translated",
        ),
        migrations.AddField(
            model_name="chapter",
            name="status",
            field=models.CharField(
                choices=[
                    ("ON_TOONKOR", "On Toonkor"),
                    ("DOWNLOAD", "Downloading"),
                    ("DOWNLOAD_TRANSLATE", "Downloading & Translating"),
                ],
                default="ON_TOONKOR",
                max_length=20,
            ),
        ),
    ]
