# Generated by Django 5.1 on 2024-09-05 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("toonkor_collector2", "0008_manhwa_chapters_num"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="manhwa",
            name="author",
        ),
        migrations.RemoveField(
            model_name="manhwa",
            name="en_author",
        ),
    ]
