# Generated by Django 5.1 on 2024-09-08 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toonkor_collector2", "0011_alter_chapter_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapter",
            name="status",
            field=models.CharField(
                choices=[
                    ("On Toonkor", "On Toonkor"),
                    ("Downloaded", "Downloaded"),
                    ("Translated", "Translated"),
                ],
                default="On Toonkor",
                max_length=20,
            ),
        ),
    ]
