# Generated by Django 5.1 on 2024-09-10 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toonkor_collector2", "0012_alter_chapter_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="manhwa",
            old_name="slug",
            new_name="toonkor_id",
        ),
        migrations.AddField(
            model_name="chapter",
            name="title",
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
