# Generated by Django 5.1 on 2024-09-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toonkor_collector2", "0014_chapter_toonkor_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="upload_date",
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
