# Generated by Django 5.1 on 2024-09-10 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("toonkor_collector2", "0016_remove_chapter_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chapter",
            old_name="upload_date",
            new_name="date_upload",
        ),
    ]
