# Generated by Django 5.1 on 2024-09-11 16:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toonkor_collector2", "0017_rename_upload_date_chapter_date_upload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapter",
            name="date_upload",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
