# Generated by Django 5.1 on 2024-09-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toonkor_collector2", "0018_alter_chapter_date_upload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapter",
            name="date_upload",
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
