# Generated by Django 5.1 on 2024-09-14 23:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toonkor_collector2", "0019_alter_chapter_date_upload"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chapter",
            name="manhwa",
        ),
        migrations.RemoveField(
            model_name="manhwa",
            name="chapters_num",
        ),
        migrations.AddField(
            model_name="chapter",
            name="manhwa_id",
            field=models.CharField(default=django.utils.timezone.now, max_length=512),
            preserve_default=False,
        ),
    ]
