# Generated by Django 5.1 on 2024-09-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "toonkor_collector2",
            "0020_remove_chapter_manhwa_remove_manhwa_chapters_num_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ToonkorSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=512)),
                ("url", models.URLField(default="https://toonkor434.com")),
            ],
        ),
    ]
