# Generated by Django 5.1 on 2024-09-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toonkor_collector2", "0021_toonkorsettings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chapter",
            name="status",
        ),
        migrations.AddField(
            model_name="chapter",
            name="download_status",
            field=models.CharField(
                choices=[
                    ("NOT_READY", "Not Ready"),
                    ("LOADING", "Loading"),
                    ("READY", "Ready"),
                ],
                default="NOT_READY",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="chapter",
            name="translation_status",
            field=models.CharField(
                choices=[
                    ("NOT_READY", "Not Ready"),
                    ("LOADING", "Loading"),
                    ("READY", "Ready"),
                ],
                default="NOT_READY",
                max_length=20,
            ),
        ),
    ]
