# Generated by Django 5.1 on 2024-09-19 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "toonkor_collector2",
            "0022_remove_chapter_status_chapter_download_status_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapter",
            name="download_status",
            field=models.CharField(
                choices=[
                    ("NOT_READY", "Not Ready"),
                    ("LOADING", "Loading"),
                    ("READY", "Ready"),
                    ("REMOVING", "Removing"),
                ],
                default="NOT_READY",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="translation_status",
            field=models.CharField(
                choices=[
                    ("NOT_READY", "Not Ready"),
                    ("LOADING", "Loading"),
                    ("READY", "Ready"),
                    ("REMOVING", "Removing"),
                ],
                default="NOT_READY",
                max_length=20,
            ),
        ),
    ]
